name: acg-test
on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run AzureCostGuard Action
        uses: ./ # local action
        with:
          location: 'eastus'
          deep-scan: 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # MVP mode uses a default subscription ID for catalog pricing
          AZURE_SUBSCRIPTION_ID: '00000000-0000-0000-0000-000000000000' 